# If you install goreleaser you can validate this configuration with:
# 'goreleaser check -f .goreleaser.yml'

# https://goreleaser.com/customization/changelog
changelog:
  # Disable posting of the changelog.
  skip: true

checksum:
  # Tag will always be v.0.0.0 so we provide a name template to achieve the
  # desired format.
  name_template: boulder-release-{{ time "2006-01-02"  }}-checksum.txt

# https://goreleaser.com/customization/archive
# Each item in the archives list is interpreted as a separate archive to be
# generatated. If you encounter something like "invalid config: found 2 archives
# with the ID 'default', please fix your config" you've added a new entry to
# this list (likely on accident).
archives:
    # Version will always be 1.0.0 so we provide a name template to achieve the
    # desired format.
  - name_template: boulder-release-{{ time "2006-01-02" }}-{{ .ShortCommit }}-{{ .Os }}-{{ .Arch }}
    replacements:
      amd64: x86_64

# https://goreleaser.com/customization/nfpm
nfpms:
  - id: boulder-nfpm
    builds:
      - boulder
    file_name_template: boulder-release-{{ time "2006-01-02" }}-1.0.0-{{ .ShortCommit }}-{{ .Os }}-{{ .Arch }}
    package_name: boulder
    maintainer: Community
    vendor: ISRG
    homepage: https://github.com/letsencrypt/boulder
    description: "Boulder is an ACME-compatible X.509 Certificate Authority"
    license: "Mozilla Public License v2.0"
    replacements:
      amd64: x86_64
    formats:
      - deb
    epoch: "1"
    bindir: /opt/boulder
    contents:
      - src: /opt/boulder/boulder
        dst: /opt/boulder/boulder-va
        type: "symlink"
    

# https://goreleaser.com/customization/build
builds:
  - &opts
    id: boulder
    main: ./cmd/boulder
    binary: "boulder"
    env:
      - GO111MODULE=on
      - CGO_ENABLED=1
      - GOFLAGS=-mod=vendor
      - GOBIN=./bin
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      # Env.HOSTNAME is not populated by GitHub Actions Runners
      - -X "github.com/letsencrypt/boulder/core.BuildHost={{ .Env.USER }}@github-actions-runner"
      - -X "github.com/letsencrypt/boulder/core.BuildID={{ .ShortCommit }}"
      - -X "github.com/letsencrypt/boulder/core.BuildTime={{ .Date }}"
  
  - <<: *opts
    id: ct-test-srv
    main: ./test/ct-test-srv
    binary: "ct-test-srv"
