# https://goreleaser.com/customization/changelog
changelog:
  # Disable posting of the changelog.
  skip: true

checksum:
  # Tag will always be v.0.0.0 so we provide a name template to achieve the
  # desired format.
  name_template: boulder-release-{{ time "2006-01-02"  }}-checksum.txt

# https://goreleaser.com/customization/archive
archives:
  # Only the binary will be uploaded.
  - format: binary
    # Tag will always be v.0.0.0 so we provide a name template to achieve the
    # desired format.
    name_template: boulder-release-{{ time "2006-01-02"  }}_{{ .Os }}_{{ .Arch }}
    replacements:
      amd64: x86_64

# https://goreleaser.com/customization/nfpm
nfpms:
  - id: boulder-nfpm
    package_name: boulder
    # Tag will always be v.0.0.0 so we provide a name template to achieve the
    # desired format.
    file_name_template: boulder-release-{{ time "2006-01-02" }}_{{ .Os }}_{{ .Arch }}
    builds:
      - boulder-build
    maintainer: boulder <boulder@letsencrypt.org>
    vendor: ISRG
    homepage: https://letsencrypt.org
    replacements:
      amd64: x86_64
    formats:
      - deb

# https://goreleaser.com/customization/build
builds:
  - id: "boulder-build"
    main: ./cmd/boulder
    env:
      - GO111MODULE=on
      - CGO_ENABLED=1
      - GOFLAGS=-mod=vendor
    binary: "boulder"
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -X "github.com/letsencrypt/boulder/core.BuildID={{ .ShortCommit }}"
      # Env.HOSTNAME is not populated by GitHub Actions Runners
      - -X "github.com/letsencrypt/boulder/core.BuildHost={{ .Env.USER }}@github-actions-runner"
      - -X "github.com/letsencrypt/boulder/core.BuildTime={{ .Date }}"