name: release

on:
  # Allows you to run this workflow manually from the 'Actions' tab.
  workflow_dispatch:

  # Runs automatically when a tag beginning with 'release-' is pushed.
  push:
    tags:
      - v*
jobs:
  release:
    # Update this when we update the version of linux used in in production.
    runs-on: ubuntu-20.04
    name: release

    steps:
      - name: setup go
        uses: actions/setup-go@v2
        with:
          # Update this when we update the version of linux used in in
          # production.
          go-version: 1.17.7

      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: build and release
        uses: goreleaser/goreleaser-action@v2
        with:
          # release: posts a GitHub release with the resulting artifact(s)
          args: release --rm-dist

          # v0.123 is the last version that allowed you to disable semver.
          version: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
