name: Build and Release
on:
  # Runs automatically when a tag beginning with 'release-' is pushed.
  push:
    tags:
      - release-*
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  gh-release:
    runs-on: ubuntu-20.04
    env:
      BOULDER_TOOLS_TAG: go1.17.7_2022-02-10

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: build and release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # https://cli.github.com/manual/gh_release_create
        run: |
          ./make-deb.sh
          gh release create "${GITHUB_REF_NAME}" *.deb
