name: release

on:
  # Runs automatically when a tag beginning with 'v1.0.0' is pushed.
  push:
    tags:
      - v1.0.0
jobs:
  release:
    # Update this when we update the version of linux used in in production.
    runs-on: ubuntu-20.04
    name: release

    steps:
      - name: setup go
        uses: actions/setup-go@v2
        with:
          # Update this when we update the version of linux used in in
          # production.
          go-version: 1.17.7

      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: build and release
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --rm-dist
          version: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
